---
- name: Check if image is already loaded
  gather_facts: no
  become: yes
  hosts: t202
  tasks: 
    - name: asd
      community.docker.docker_image_load:
      path: /opt/asureo/nginx_alpine.tar
           

