---
- name: Change pass for postgres user
  hosts: t202
  gather_facts: no
  become_user: postgres
  become_method: sudo
  become: yes
  tasks:
    - service:
        name: postgrespro-std-16
        state: started

    - shell: psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
