---   
- name: ADD postgres to sudoers
  lineinfile:
    path: /etc/sudoers
    regexp: '^postgres ALL='
    line: 'postgres ALL=(ALL) NOPASSWD: ALL'
    state: present

- name: Change pass for postgres user
  become_user: postgres
  postgresql_user:
    login_unix_socket: /tmp
    name: postgres
    password: postgres

- name: Change host in pg_hba.conf
  lineinfile:
    path: /var/lib/pgpro/std-16/data/pg_hba.conf
    state: present
    regexp: '^host\s+all\s+all\s+127\.0\.0\.1/32'
    line: 'host	all		all		0.0.0.0/0		trust'
    backrefs: yes
    backup: yes

- name: Change listen_addresses in postgresql.conf
  lineinfile:
    path: /var/lib/pgpro/std-16/data/postgresql.conf
    state: present
    regexp: '^#listen_addresses = '
    line: listen_addresses = '*'
    backup: yes
    backrefs: yes

- name: Create database
  become_user: postgres
  postgresql_db: 
    login_unix_socket: /tmp
    name: asureo

- name: Restart service to apply confs
  service:
    name: postgrespro-std-16
    state: restarted

