---
- name: Remove sources.list
  file:
    path: /etc/apt/sources.list
    state: absent

- name: "Add repos"
  lineinfile:
    path: /etc/apt/sources.list 
    line: "{{ item }}" 
    create: yes
  with_items:
    - "deb http://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-main/     1.7_x86-64 main contrib non-free"
    - "deb http://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-update/   1.7_x86-64 main contrib non-free"
    - "deb http://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-base/     1.7_x86-64 main contrib non-free"
    - "deb http://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-extended/ 1.7_x86-64 main contrib non-free"
    - "deb https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-extended/ 1.7_x86-64 astra-ce"
  notify: Update apt

